// Generated by emjet_histo_code.py
// Edit with caution!
class EmJetHistos
{
 public:
  EmJetHistos();
  ~EmJetHistos();
  /*[[[cog
    import emjet_histo_code as mod
    mod.generate_vbin_decl()
    mod.generate_histo_decl()
    mod.generate_histo_vector_decl()
    ]]]*/
  //[[[end]]]
};

EmJetHistos::EmJetHistos()
{
  /*[[[cog
    mod.generate_histo_init()
    mod.generate_histo_vector_init()
    ]]]*/
    //[[[end]]]
}

EmJetHistos::~EmJetHistos()
{
  /*[[[cog
    mod.generate_histo_dest()
    mod.generate_histo_vector_dest()
    ]]]*/
  //[[[end]]]
}
